### PR TITLE
Fix lpurge build against lustre >=2.12

### LINKED ISSUE #17: Doesn't build with Lustre 2.12.2
This doesn't build against current lustre 2.12.2:
```
lpurge.c:617:43: error: invalid application of 'sizeof' to incomplete type 'struct lov_user_mds_data_v3'
                                    sizeof(struct lov_user_mds_data_v3) +
                                           ^~~~~~
```
lov_user_mds_data_v3 was removed in this commit: https://git.whamcloud.com/?p=fs/lustre-release.git;a=commit;h=6712478e79588e73e28c7ccac3afc7ac2368a4f3
See https://jira.whamcloud.com/browse/LU-6401

### PR DESCRIPTION
**Pull request by ofaaland**
Lustre 2.12 changes result in the following build errors.

> lpurge.c: In function 'llapi_stat_mds':
> lpurge.c:617:43: error: invalid application of 'sizeof' to incomplete type 'struct lov_user_mds_data_v3'
>                                     sizeof(struct lov_user_mds_data_v3) +
>                                            ^
> lpurge.c:617:43: error: invalid application of 'sizeof' to incomplete type 'struct lov_user_mds_data_v3'
>                                     sizeof(struct lov_user_mds_data_v3) +
>                                            ^
> lpurge.c:620:57: error: 'struct lov_user_mds_data_v2' has no member named 'lmd_st'
>          lstat_t *ls = &((struct lov_user_mds_data *)buf)->lmd_st;
>                                                          ^

Modify configure.ac to detect whether the Lustre 2.12 header location
exists, linux/lustre/lustre_user.h.

Create a lustre 2.12-suitable version of llapi_stat_mds() which uses
lov_user_mds_data and expects to get back a lustre_statx structure
instead of an lstat one.  Determine which version of llapi_stat_mds() to
use based on the presence of the new header file.

The lustre_statx structure has times in a new format, statx_timestamp,
where the tv_sec is seconds since the epoch, as with time_t, but
which is 64 bits long to prevent year 2038 wrapping.

Before 2038, the time_t and statx_timestamp.tv_sec have the same value.
Since I do not expect lpurge to be around that long, copy those low
order bits into the existing atime, ctime, and mtime structure
members.

The relevant lustre change:
https://git.whamcloud.com/?p=fs/lustre-release.git;a=commit;h=6712478e79588e73e28c7ccac3afc7ac2368a4f3
https://jira.whamcloud.com/browse/LU-6401

Fixes #17

Signed-off-by: Olaf Faaland <faaland1@llnl.gov>

### CODE REVIEW

**Comment by ofaaland** [comment]
I built and tested this against both Lustre 2.10 and 2.10 on Opal (it has some nodes running 2.10 and some 2.12)
Worked correctly.

File: src/lpurge.c [hunk 1]
```diff
@@ -610,6 +610,57 @@ purge(const char *path, time_t thresh, struct elist_struct *elist,
...
 
+#ifdef HAVE_LINUX_LUSTRE_LUSTRE_USER_H
+
+/* Lustre >= 2.12 */
+static int
+llapi_stat_mds(int fd, char *fname, struct stat *sb)
+{
+        const size_t bufsize = MAX(MAXPATHLEN,
+                                   sizeof(struct lov_user_mds_data) +
+                                   sizeof(struct lov_user_ost_data_v1) * 2000);
```
Comment (defaziogiancarlo) [inline src/lpurge.c:621]: Nitpick: Should this be "lov_user_ost_data" to be consistent with dropping the version from "lov_user_mds_data"?

File: src/lpurge.c [hunk 2]
```diff
@@ -610,6 +610,57 @@ purge(const char *path, time_t thresh, struct elist_struct *elist,
...
+
+        if (strlen(fname) >= bufsize) {
+                errno = EINVAL;
+                goto done;
+        }
+
+        /* Usage: ioctl(fd, IOC_MDC_GETFILEINFO, buf)
+         * IN:  fd   open file descriptor of file's parent directory
+         * IN:  buf  file name (no path)
+         * OUT: buf  lstat_t
```
Comment (defaziogiancarlo) [inline src/lpurge.c:634]: `lstatx_t`

File: src/lpurge.c [hunk 3]
```diff
@@ -610,6 +610,57 @@ purge(const char *path, time_t thresh, struct elist_struct *elist,
...
+         */
+        strncpy(buf, fname, bufsize);
+        if ((ret = ioctl(fd, IOC_MDC_GETFILEINFO, buf)) < 0)
+                goto done;
+
+        /* Copy 'lstat_t' to 'struct stat'
```
Comment (defaziogiancarlo) [inline src/lpurge.c:640]: `copy 'lstatx_t' to 'struct stat' `

File: src/lpurge.c [hunk 4]
```diff
@@ -610,6 +610,57 @@ purge(const char *path, time_t thresh, struct elist_struct *elist,
...
+        sb->st_mode    = lsx->stx_mode;
+        sb->st_nlink   = lsx->stx_nlink;
+        sb->st_uid     = lsx->stx_uid;
+        sb->st_gid     = lsx->stx_gid;
+        sb->st_rdev    = makedev(lsx->stx_rdev_major, lsx->stx_rdev_minor);
+        sb->st_size    = lsx->stx_size;
+        sb->st_blksize = lsx->stx_blksize;
+        sb->st_blocks  = lsx->stx_blocks;
+
+        /* non-2038 safe workaround, I expect lpurge to go away. */
```
Comment (defaziogiancarlo) [inline src/lpurge.c:653]: used `stx_atime` for all 3 times

File: src/lpurge.c (hunk 1 above)
Comment (ofaaland) [reply src/lpurge.c:621]: Yes, that makes sense.  Fixed.

File: src/lpurge.c (hunk 2 above)
Comment (ofaaland) [reply src/lpurge.c:634]: fixed

File: src/lpurge.c (hunk 4 above)
Comment (ofaaland) [reply src/lpurge.c:653]: fixed.  Thanks for catching that.

File: src/lpurge.c (hunk 3 above)
Comment (ofaaland) [reply src/lpurge.c:640]: fixed

**Comment by ofaaland** [comment]
I've pushed an updated version which fixes those issues.  Please take a look again, thanks.

**Comment by ofaaland** [comment]
Landed via
* bf69430 Fix lpurge build against lustre >=2.12
