### ISSUE TITLE
Doesn't build with Lustre 2.12.2

### ISSUE THREAD

**Issue by LaHaine** [LLNL/lustre-tools-llnl#17]
This doesn't build against current lustre 2.12.2:
```
lpurge.c:617:43: error: invalid application of 'sizeof' to incomplete type 'struct lov_user_mds_data_v3'
                                    sizeof(struct lov_user_mds_data_v3) +
                                           ^~~~~~
```
lov_user_mds_data_v3 was removed in this commit: https://git.whamcloud.com/?p=fs/lustre-release.git;a=commit;h=6712478e79588e73e28c7ccac3afc7ac2368a4f3
See https://jira.whamcloud.com/browse/LU-6401

**Comment by ofaaland** [comment]
Hi @LaHaine , do you use lpurge at your site?  I'm fixing this error for now, but considering dropping lpurge next time an issue comes up.  I believe there are now better ways to accomplish what lpurge does.  Thanks

**Comment by LaHaine** [comment]
No, I'm not using lpurge, I just saw this error and thought it useful to tell you.

**Comment by ofaaland** [comment]
> No, I'm not using lpurge, I just saw this error and thought it useful to tell you.

Yes, very much so.  Thanks!

**Comment by ofaaland** [comment]
Fixed in 1.8.17
* bf69430 Fix lpurge build against lustre >=2.12
